[env:uno-speed]
platform = atmelavr
board = uno
framework = arduino
; Speed-optimized build w/o debug or runtime stats
monitor_speed = 115200
monitor_port = /dev/ttyACM0
upload_port = /dev/ttyACM0
build_flags =

  -DLW232_RX_BUFFER_SIZE=32
  -DLW232_DEFAULT_UART_BAUD_INDEX=0x00
  -DENABLE_CAN_DEBUG_LOGGING=0
  -DDISABLE_RUNTIME_STATS=1
  -Os
  -flto
  
[env:uno-debug]
platform = atmelavr
board = uno
framework = arduino
build_type = debug

; Serial Monitor
monitor_speed = 115200
monitor_port = /dev/ttyACM0
upload_port = /dev/ttyACM0

build_flags =
  ; --- MEMORY SAFETY ---
  ; CRITICAL: Keep buffer to 32 even for debug! 
  ; 64 frames (1152 bytes) + Debug Overhead (Stack) = High Crash Risk on Uno.
  -DLW232_RX_BUFFER_SIZE=16
  
  ; --- DEBUGGING FEATURES ---
  ; Enable verbose Serial logging for CAN events
  -DENABLE_CAN_DEBUG_LOGGING=1
  ; Enable runtime statistics (commands/sec, errors, etc.)
  -DDISABLE_RUNTIME_STATS=0
  
  ; --- COMPILER OPTIONS ---
  ; -O0: No optimization. Best for GDB/Stepping, but slowest execution.
  ; WARNING: This may miss fast CAN bursts due to CPU slowness.
  -O0
  ; -g3: Include maximum debug information (macros, etc.)
  -g3
  ; Catch all warnings to fix logic errors early
  -Wall
  -Wextra
